import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { getApiError } from '../features/auth/auth.api';
import '../styles/list.css';

export default function ListPage({ title, API, createLink, detailPath = '/view' }) {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [totalPages, setTotalPages] = useState(1);
  const fetchItems = async () => { try { setLoading(true); setError(''); const response = await API.list(page, 10, search || undefined); setItems(response.data.items || response.data.customers || response.data.garments || response.data.orders || response.data.suppliers || response.data.tailors || []); setTotalPages(Math.max(1, Math.ceil((response.data.pagination?.total || 0) / 10))); } catch (requestError) { setError(getApiError(requestError, 'Unable to load records')); } finally { setLoading(false); } };
  useEffect(() => { fetchItems(); }, [page, search]);
  const handleDelete = async (id) => { if (!window.confirm(`Delete this ${title.slice(0, -1).toLowerCase()}?`)) return; try { await API.delete(id); if (items.length === 1 && page > 1) setPage((current) => current - 1); else fetchItems(); } catch (requestError) { setError(getApiError(requestError, 'Delete failed')); } };
  return <main className="list-container"><div className="list-header"><div><p className="section-kicker">Workspace</p><h1>{title}</h1></div>{createLink && <Link to={createLink} className="btn btn-primary">Add new</Link>}</div><div className="list-filters"><label className="sr-only" htmlFor={`${title}-search`}>Search {title}</label><input id={`${title}-search`} type="search" placeholder={`Search ${title.toLowerCase()}...`} value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} className="search-input" /></div>{error && <div className="list-alert" role="alert">{error}</div>}{loading ? <p className="list-status">Loading...</p> : items.length === 0 ? <p className="list-status">No {title.toLowerCase()} found.</p> : <><div className="items-table">{items.map((item, index) => <div key={item._id} className="item-row"><span className="item-number">{(page - 1) * 10 + index + 1}</span><span className="item-name">{item.firstName ? `${item.firstName} ${item.lastName}` : item.name || item.orderNumber || 'Record'}</span><span className="item-info">{item.email || item.category || item.status || item.phone || '—'}</span><div className="item-actions"><Link to={`${detailPath}/${item._id}`} className="btn btn-small">View</Link><button type="button" onClick={() => handleDelete(item._id)} className="btn btn-small btn-danger">Delete</button></div></div>)}</div><div className="pagination"><button type="button" onClick={() => setPage((current) => Math.max(1, current - 1))} disabled={page === 1}>Previous</button><span>Page {page} of {totalPages}</span><button type="button" onClick={() => setPage((current) => Math.min(totalPages, current + 1))} disabled={page >= totalPages}>Next</button></div></>}</main>;
}
